// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
package org.usfirst.frc1583.CommandRobot.commands;
import edu.wpi.first.wpilibj.Timer;
import org.usfirst.frc1583.CommandRobot.Robot;
/**
 *
 */
public class ShuttleToTopTimedCommand extends ShuttleMovementBaseCommand
{
    private double delay;
    private Timer timer;

    public ShuttleToTopTimedCommand( double delay )
    {
        this.delay = delay;
        // Use requires() here to declare subsystem dependencies
        // eg. requires(chassis);
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        requires(Robot.armSubsystem);
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    }
    // Called just before this Command runs the first time
    protected void initialize()
    {
        resetCounter();
        timer = new Timer();
        timer.start();
    }
    // Called repeatedly when this Command is scheduled to run
    protected void execute()
    {
        Robot.armSubsystem.shuttleUp();
    }
    // Make this return true when this Command no longer needs to run execute()
    protected boolean isFinished()
    {
        updateCounter();
        return timer.get() > delay;
    }
    // Called once after isFinished returns true
    protected void end()
    {
        timer.stop();
        Robot.armSubsystem.stop();
    }
    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    protected void interrupted()
    {
        timer.stop();
        Robot.armSubsystem.stop();
    }
}
