// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
package org.usfirst.frc1583.CommandRobot;
import org.usfirst.frc1583.CommandRobot.actions.*;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import org.usfirst.frc1583.CommandRobot.sequences.Climb30CompleteSequence;
import org.usfirst.frc1583.CommandRobot.sequences.Climb30Sequence1;
import org.usfirst.frc1583.CommandRobot.steps.Climb30Step1a;
import org.usfirst.frc1583.CommandRobot.steps.Climb30Step1b;
import org.usfirst.frc1583.CommandRobot.steps.Climb30Step1c;
import org.usfirst.frc1583.CommandRobot.steps.Climb30Step1d;
import org.usfirst.frc1583.CommandRobot.sequences.Climb30Sequence2;
import org.usfirst.frc1583.CommandRobot.steps.Climb30Step2a;
import org.usfirst.frc1583.CommandRobot.steps.Climb30Step2b;
import org.usfirst.frc1583.CommandRobot.sequences.Climb30Sequence3;
import org.usfirst.frc1583.CommandRobot.steps.Climb30Step3a;
import org.usfirst.frc1583.CommandRobot.steps.Climb30Step3b;
import org.usfirst.frc1583.CommandRobot.sequences.Climb30Sequence4;
import org.usfirst.frc1583.CommandRobot.steps.Climb30Step4a;
import org.usfirst.frc1583.CommandRobot.sequences.Climb30Sequence5;
import org.usfirst.frc1583.CommandRobot.steps.Climb30Step5a;
import org.usfirst.frc1583.CommandRobot.sequences.ResetSequence;
import org.usfirst.frc1583.CommandRobot.steps.Climb20Step1a;
import org.usfirst.frc1583.CommandRobot.steps.Climb20Step2a;
import org.usfirst.frc1583.CommandRobot.steps.Climb20Step3a;
/**
 * This class is the glue that binds the controls on the physical operator
 * interface to the commands and command groups that allow control of the robot.
 */
public class OI
{
    //// CREATING BUTTONS
    // One type of button is a joystick button which is any button on a joystick.
    // You create one by telling it which joystick it's on and which button
    // number it is.
    // Joystick stick = new Joystick(port);
    // Button button = new JoystickButton(stick, buttonNumber);
    // Another type of button you can create is a DigitalIOButton, which is
    // a button or switch hooked up to the cypress module. These are useful if
    // you want to build a customized operator interface.
    // Button button = new DigitalIOButton(1);
    // There are a few additional built in buttons you can use. Additionally,
    // by subclassing Button you can create custom triggers and bind those to
    // commands the same as any other Button.
    //// TRIGGERING COMMANDS WITH BUTTONS
    // Once you have a button, it's trivial to bind it to a button in one of
    // three ways:
    // Start the command when the button is pressed and let it run the command
    // until it is finished as determined by it's isFinished method.
    // button.whenPressed(new ExampleCommand());
    // Run the command while the button is being held down and interrupt it once
    // the button is released.
    // button.whileHeld(new ExampleCommand());
    // Start the command when the button is released  and let it run the command
    // until it is finished as determined by it's isFinished method.
    // button.whenReleased(new ExampleCommand());
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
//    public DigitalIOButton abortButton;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public OI()
    {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
//        abortButton = new DigitalIOButton(1);
//        abortButton.whenPressed(new AbortAction());
	    
        // SmartDashboard Buttons
//        SmartDashboard.putData("AbortCommand", new AbortCommand());
//        SmartDashboard.putData("Autonomous Command", new AutonomousCommand());
        SmartDashboard.putData("ShuttleToTopAction", new ShuttleToTopAction());
        SmartDashboard.putData("ShuttleToBottomAction", new ShuttleToBottomAction());
        SmartDashboard.putData("CGCenterAction", new CGCenterAction());
        SmartDashboard.putData("CGFullBackAction", new CGFullBackAction());
        SmartDashboard.putData("CGFullForwardAction", new CGFullForwardAction());
        SmartDashboard.putData("CGHalfBackAction", new CGHalfBackAction());
        SmartDashboard.putData("CGHalfForwardAction", new CGHalfForwardAction());
        SmartDashboard.putData("Climb30Step1a", new Climb30Step1a());
        SmartDashboard.putData("Climb30Step1b", new Climb30Step1b());
        SmartDashboard.putData("Climb30Step1c", new Climb30Step1c());
        SmartDashboard.putData("Climb30Step1d", new Climb30Step1d());
        SmartDashboard.putData("Climb30Step2a", new Climb30Step2a());
        SmartDashboard.putData("Climb30Step2b", new Climb30Step2b());
        SmartDashboard.putData("Climb30Step3a", new Climb30Step3a());
        SmartDashboard.putData("Climb30Step3b", new Climb30Step3b());
        SmartDashboard.putData("Climb30Step4a", new Climb30Step4a());
        SmartDashboard.putData("Climb30Step5a", new Climb30Step5a());
        SmartDashboard.putData("Climb20Step1a", new Climb20Step1a());
        SmartDashboard.putData("Climb20Step2a", new Climb20Step2a());
        SmartDashboard.putData("Climb20Step3a", new Climb20Step3a());
        SmartDashboard.putData("ResetSequence", new ResetSequence());
        SmartDashboard.putData("Climb30Sequence1", new Climb30Sequence1());
        SmartDashboard.putData("Climb30Sequence2", new Climb30Sequence2());
        SmartDashboard.putData("Climb30Sequence3", new Climb30Sequence3());
        SmartDashboard.putData("Climb30Sequence4", new Climb30Sequence4());
        SmartDashboard.putData("Climb30Sequence5", new Climb30Sequence5());
        SmartDashboard.putData( "30 Point Climb", new Climb30CompleteSequence() );
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
}
