// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
package org.usfirst.frc1583.CommandRobot.actions;
import edu.wpi.first.wpilibj.command.Command;
import org.usfirst.frc1583.CommandRobot.Robot;
/**
 *
 */
public class CGCenterAction extends CGBaseAction
{
    public CGCenterAction()
    {
//        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
//        requires(Robot.bodyPIDSubsystem);
//    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        super();
        System.out.println("In CGCenterAction");
    }
    // Called just before this Command runs the first time
    protected void initialize()
    {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INITIALIZE
//        Robot.bodyPIDSubsystem.enable();
//        Robot.bodyPIDSubsystem.setSetpoint(Robot.bodyPIDSubsystem.CG_CENTER);
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INITIALIZE
//        super.initialize();
//        Robot.bodyPIDSubsystem.setSetpoint(Robot.bodyPIDSubsystem.CG_CENTER);
//        super.initialize();
        Robot.bodySubsystem.setSetpoint( Robot.bodySubsystem.CG_CENTER);
        System.out.println("In initialize");
    }
//     Called repeatedly when this Command is scheduled to run
//    protected void execute()
//    {
//        System.out.println("In execute");
//    }
    // Make this return true when this Command no longer needs to run execute()
//    protected boolean isFinished()
//    {
//        System.out.println("In isFinished");
//        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ISFINISHED
////        return Robot.bodyPIDSubsystem.onTarget();
//    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ISFINISHED
//        Robot.bodySubsystem.onTarget();
//    }
    // Called once after isFinished returns true
//    protected void end()
//    {
////        Robot.bodyPIDSubsystem.disable();
//        System.out.println("In end");
//    }
    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
//    protected void interrupted()
//    {
////        Robot.bodyPIDSubsystem.disable();
//        System.out.println("In interrupted");
//    }
}
